# 网上办事数据库配置
wsbs:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@47.98.63.50:1521:ORCL
    username: APL_YGZW_POWER
    password: APL_YGZW_POWER
    mapper-location: classpath:mapper/wsbs/*.xml

# 政务网数据库配置
zww:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@47.98.63.50:1521:ORCL
    username: APL_YGZW_ONLINE
    password: APL_YGZW_ONLINE
    mapper-location: classpath:mapper/zww/*.xml