server:
  port: 9999

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/quick_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: root
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
#      driver-class-name: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver # MySql8.x
  redis:
    host: 192.168.10.45
    timeout: 3000


mybatis:
  type-aliases-package: com.yangb.project.quickdev.entity
  mapper-locations: classpath:mapper/*.xml

