
spring:
  datasource:
    druid:
      url: jdbc:mysql://47.98.63.50:3306/shop_goods?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: SHOP_GOODS
      password: Apl@2020!
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
#      driver-class-name: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver # MySql8.x
  security:
    filter:
      order: 10

mybatis:
  type-aliases-package: com.yangb.project.quickdev.entity
  mapper-locations: classpath:mapper/*.xml

server:
  port: 9000
  servlet:
    context-path: /mall-api
